# The petstore database should be created for you, if not here is the command:
# psql -c "create database petstore;" -U customers
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customers
  labels:
    app: customers
spec:
  serviceName: "customers"
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                  configMapKeyRef:
                    name: postgres-config
                    key: postgres_db
          volumeMounts:
          - name: customers-storage
            mountPath: /var/lib/postgresql
          resources:
            limits:
              cpu: "0.50"
              memory: "128Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
        # emptyDir: {}